name: PowerShell Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install PowerShell
      run: |
        echo "Installing PowerShell Core..."
        sudo apt-get update
        sudo apt-get install -y powershell
        pwsh --version

    - name: Install Pester
      shell: pwsh
      run: |
        Write-Output "Installing Pester module..."
        Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
        Get-Module -ListAvailable Pester | Format-Table Name,Version

    - name: Run Pester Tests with Verbose Output
      shell: pwsh
      run: |
        Write-Output "Starting Pester tests..."
        $results = Invoke-Pester -Path "FileOperations.Tests.ps1" -CodeCoverage "FileOperations.ps1" -OutputFile "test-results.xml" -OutputFormat NUnitXml -PassThru -Verbose
        Write-Output "Test Summary:"
        Write-Output "  Passed: $($results.PassedCount)"
        Write-Output "  Failed: $($results.FailedCount)"
        Write-Output "  Total: $($results.TotalCount)"
        $coverage = $results.CodeCoverage.NumberOfCommandsAnalyzed > 0 ? (($results.CodeCoverage.NumberOfCommandsHit / $results.CodeCoverage.NumberOfCommandsAnalyzed) * 100) : 0
        Write-Output "Code Coverage Report:"
        Write-Output "  Commands Analyzed: $($results.CodeCoverage.NumberOfCommandsAnalyzed)"
        Write-Output "  Commands Hit: $($results.CodeCoverage.NumberOfCommandsHit)"
        Write-Output "  Coverage Percentage: $coverage%"
        if ($results.FailedCount -gt 0) {
          Write-Output "Tests failed. Exiting with error."
          exit 1
        } else {
          Write-Output "All tests passed successfully!"
        }

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml
