name: PowerShell Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: Ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install PowerShell
      run: |
        echo "Installing PowerShell Core..."
        sudo apt-get update
        sudo apt-get install -y pwsh
        pwsh --version

    - name: Install Pester
      shell: pwsh
      run: |
        Write-Output "Installing Pester module..."
        Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
        Get-Module -ListAvailable Pester | Format-Table Name,Version

    - name: Run Pester Tests with Verbose Output
      shell: pwsh
      run: |
        Write-Output "Starting Pester tests..."
        $results = Invoke-Pester -Path "TaskManager.tests.ps1" -CodeCoverage "TaskManager.ps1" -OutputFile "test-results.xml" -OutputFormat NunitXML -PassThru -Verbosity Detailed
        Write-Output "Test Summary:"
        Write-Output "  Passed: $($results.PassedCount)"
        Write-Output "  Failed: $($results.FailedCount)"
        Write-Output "  Total: $($results.TotalCount)"
        if ($results.CodeCoverage.NumberOfCommandsAnalyzed -gt 0) {
          $coverage = ($results.CodeCoverage.NumberOfCommandsHit / $results.CodeCoverage.NumberOfCommandsAnalyzed) * 100
        } else {
          $coverage = 0
        }
        Write-Output "Code Coverage Report:"
        Write-Output "  Commands Analyzed: $($results.CodeCoverage.NumberOfCommandsAnalyzed)"
        Write-Output "  Commands Hit: $($results.CodeCoverage.NumberOfCommandsHit)"
        Write-Output "  Coverage Percentage: $coverage%"
        if ($results.FailedCount -gt 0) {
          Write-Output "Tests failed. Exiting with error."
          exit 1
        } else {
          Write-Output "All tests passed successfully!"
        }

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml