name: Pester Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PowerShell
        run: |
          echo "Installing PowerShell Core..."
          sudo apt-get update
          sudo apt-get install -y powershell
          pwsh --version

      - name: Install Pester
        run: pwsh -command "Install-Module -Name Pester -Force -SkipPublisherCheck"

      - name: Run Pester tests
        run: |
          mkdir -p test-results
          pwsh -command "Invoke-Pester -Path ./tests -OutputFormat NUnitXml -OutputFile ./test-results/test-results.xml"

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results/test-results.xml

      - name: Display test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:          
          files: ./test-results/test-results.xml          

