name: PowerShell Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install PowerShell
      run: |
        echo "Installing PowerShell Core..."
        sudo apt-get update
        sudo apt-get install -y powershell
        pwsh --version

    - name: Install Pester
      shell: pwsh
      run: |
        Write-Output "Installing Pester module..."
        Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
        Get-Module -ListAvailable Pester | Format-Table Name,Version

    - name: Run Pester Tests with Verbose Output
      shell: pwsh
      run: |
        Write-Output "Starting Pester tests..."
        $results = Invoke-Pester -Path "TaskManager.Tests.ps1" -CodeCoverage "TaskManager.ps1" -OutputFile "test-results.xml" -OutputFormat NunitXML -PassThru
        Write-Output "Test Summary:"
        Write-Output "  Passed: $($results.PassedCount)"
        Write-Output "  Failed: $($results.FailedCount)"
        Write-Output "  Total: $($results.TotalCount)"
        if ($results.CodeCoverage.NumberOfCommandsAnalyzed -gt 0) {
          $coverage = ($results.CodeCoverage.NumberOfCommandsHit / $results.CodeCoverage.NumberOfCommandsAnalyzed) * 100
        } else {
          $coverage = 0
        }
        Write-Output "Code Coverage Report:"
        Write-Output "  Commands Analyzed: $($results.CodeCoverage.NumberOfCommandsAnalyzed)"
        Write-Output "  Commands Hit: $($results.CodeCoverage.NumberOfCommandsHit)"